project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true

files:
  - source: /**/values/*.xml
    translation: /**/values-%android-code%/%original_file_name%
    # translate_attributes: 0
