name: Crowdin Action

on:
  push:
    branches: [ main ]
    
jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: crowdin action
      uses: crowdin/github-action@v1
      with:
        # This is the name of the git branch that Crowdin will create when opening a pull request.
        # This branch does NOT need to be manually created. It will be created automatically by the action.
        localization_branch_name: l10n_crowdin_action
        create_pull_request: true
        pull_request_title: 'New Crowdin translations'
        pull_request_body: 'New Crowdin pull request with translations'
    
        # This is the name of the git branch to with pull request will be created.
        # If not specified default repository branch will be used.
        pull_request_base_branch_name: main
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
